############################
## HUGO MODULES
## Install or uninstall themes and plugins here.
## Docs: https://gohugo.io/hugo-modules/
############################

hugoVersion:
  min: '0.167.0'
  extended: true

imports:
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-decap-cms
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5
